// Code generated by MockGen. DO NOT EDIT.
// Source: keys.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	logical "github.com/hashicorp/vault/sdk/logical"
	entities "github.com/maximfischuk/blockchain-signer-hashicorp-vault-plugin/vault/entities"
	keys "github.com/maximfischuk/blockchain-signer-hashicorp-vault-plugin/vault/operations/keys"
)

// MockKeysOperations is a mock of KeysOperations interface.
type MockKeysOperations struct {
	ctrl     *gomock.Controller
	recorder *MockKeysOperationsMockRecorder
}

// MockKeysOperationsMockRecorder is the mock recorder for MockKeysOperations.
type MockKeysOperationsMockRecorder struct {
	mock *MockKeysOperations
}

// NewMockKeysOperations creates a new mock instance.
func NewMockKeysOperations(ctrl *gomock.Controller) *MockKeysOperations {
	mock := &MockKeysOperations{ctrl: ctrl}
	mock.recorder = &MockKeysOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeysOperations) EXPECT() *MockKeysOperationsMockRecorder {
	return m.recorder
}

// CreateKey mocks base method.
func (m *MockKeysOperations) CreateKey() keys.CreateKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKey")
	ret0, _ := ret[0].(keys.CreateKeyOperation)
	return ret0
}

// CreateKey indicates an expected call of CreateKey.
func (mr *MockKeysOperationsMockRecorder) CreateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKey", reflect.TypeOf((*MockKeysOperations)(nil).CreateKey))
}

// ExistsKey mocks base method.
func (m *MockKeysOperations) ExistsKey() keys.ExistsKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsKey")
	ret0, _ := ret[0].(keys.ExistsKeyOperation)
	return ret0
}

// ExistsKey indicates an expected call of ExistsKey.
func (mr *MockKeysOperationsMockRecorder) ExistsKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsKey", reflect.TypeOf((*MockKeysOperations)(nil).ExistsKey))
}

// ListKeys mocks base method.
func (m *MockKeysOperations) ListKeys() keys.ListKeysOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeys")
	ret0, _ := ret[0].(keys.ListKeysOperation)
	return ret0
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockKeysOperationsMockRecorder) ListKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockKeysOperations)(nil).ListKeys))
}

// ReadKey mocks base method.
func (m *MockKeysOperations) ReadKey() keys.ReadKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadKey")
	ret0, _ := ret[0].(keys.ReadKeyOperation)
	return ret0
}

// ReadKey indicates an expected call of ReadKey.
func (mr *MockKeysOperationsMockRecorder) ReadKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadKey", reflect.TypeOf((*MockKeysOperations)(nil).ReadKey))
}

// MockCreateKeyOperation is a mock of CreateKeyOperation interface.
type MockCreateKeyOperation struct {
	ctrl     *gomock.Controller
	recorder *MockCreateKeyOperationMockRecorder
}

// MockCreateKeyOperationMockRecorder is the mock recorder for MockCreateKeyOperation.
type MockCreateKeyOperationMockRecorder struct {
	mock *MockCreateKeyOperation
}

// NewMockCreateKeyOperation creates a new mock instance.
func NewMockCreateKeyOperation(ctrl *gomock.Controller) *MockCreateKeyOperation {
	mock := &MockCreateKeyOperation{ctrl: ctrl}
	mock.recorder = &MockCreateKeyOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateKeyOperation) EXPECT() *MockCreateKeyOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateKeyOperation) Execute(ctx context.Context, id, curve string, metadata map[string]string) (*entities.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id, curve, metadata)
	ret0, _ := ret[0].(*entities.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateKeyOperationMockRecorder) Execute(ctx, id, curve, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateKeyOperation)(nil).Execute), ctx, id, curve, metadata)
}

// WithStorage mocks base method.
func (m *MockCreateKeyOperation) WithStorage(storage logical.Storage) keys.CreateKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.CreateKeyOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockCreateKeyOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockCreateKeyOperation)(nil).WithStorage), storage)
}

// MockReadKeyOperation is a mock of ReadKeyOperation interface.
type MockReadKeyOperation struct {
	ctrl     *gomock.Controller
	recorder *MockReadKeyOperationMockRecorder
}

// MockReadKeyOperationMockRecorder is the mock recorder for MockReadKeyOperation.
type MockReadKeyOperationMockRecorder struct {
	mock *MockReadKeyOperation
}

// NewMockReadKeyOperation creates a new mock instance.
func NewMockReadKeyOperation(ctrl *gomock.Controller) *MockReadKeyOperation {
	mock := &MockReadKeyOperation{ctrl: ctrl}
	mock.recorder = &MockReadKeyOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadKeyOperation) EXPECT() *MockReadKeyOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockReadKeyOperation) Execute(ctx context.Context, id string) (*entities.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*entities.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockReadKeyOperationMockRecorder) Execute(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockReadKeyOperation)(nil).Execute), ctx, id)
}

// WithStorage mocks base method.
func (m *MockReadKeyOperation) WithStorage(storage logical.Storage) keys.ReadKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.ReadKeyOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockReadKeyOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockReadKeyOperation)(nil).WithStorage), storage)
}

// MockExistsKeyOperation is a mock of ExistsKeyOperation interface.
type MockExistsKeyOperation struct {
	ctrl     *gomock.Controller
	recorder *MockExistsKeyOperationMockRecorder
}

// MockExistsKeyOperationMockRecorder is the mock recorder for MockExistsKeyOperation.
type MockExistsKeyOperationMockRecorder struct {
	mock *MockExistsKeyOperation
}

// NewMockExistsKeyOperation creates a new mock instance.
func NewMockExistsKeyOperation(ctrl *gomock.Controller) *MockExistsKeyOperation {
	mock := &MockExistsKeyOperation{ctrl: ctrl}
	mock.recorder = &MockExistsKeyOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExistsKeyOperation) EXPECT() *MockExistsKeyOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExistsKeyOperation) Execute(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExistsKeyOperationMockRecorder) Execute(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExistsKeyOperation)(nil).Execute), ctx, id)
}

// WithStorage mocks base method.
func (m *MockExistsKeyOperation) WithStorage(storage logical.Storage) keys.ExistsKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.ExistsKeyOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockExistsKeyOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockExistsKeyOperation)(nil).WithStorage), storage)
}

// MockDeleteKeyOperation is a mock of DeleteKeyOperation interface.
type MockDeleteKeyOperation struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteKeyOperationMockRecorder
}

// MockDeleteKeyOperationMockRecorder is the mock recorder for MockDeleteKeyOperation.
type MockDeleteKeyOperationMockRecorder struct {
	mock *MockDeleteKeyOperation
}

// NewMockDeleteKeyOperation creates a new mock instance.
func NewMockDeleteKeyOperation(ctrl *gomock.Controller) *MockDeleteKeyOperation {
	mock := &MockDeleteKeyOperation{ctrl: ctrl}
	mock.recorder = &MockDeleteKeyOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteKeyOperation) EXPECT() *MockDeleteKeyOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteKeyOperation) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteKeyOperationMockRecorder) Execute(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteKeyOperation)(nil).Execute), ctx, id)
}

// WithStorage mocks base method.
func (m *MockDeleteKeyOperation) WithStorage(storage logical.Storage) keys.DeleteKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.DeleteKeyOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockDeleteKeyOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockDeleteKeyOperation)(nil).WithStorage), storage)
}

// MockUpdateKeyOperation is a mock of UpdateKeyOperation interface.
type MockUpdateKeyOperation struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateKeyOperationMockRecorder
}

// MockUpdateKeyOperationMockRecorder is the mock recorder for MockUpdateKeyOperation.
type MockUpdateKeyOperationMockRecorder struct {
	mock *MockUpdateKeyOperation
}

// NewMockUpdateKeyOperation creates a new mock instance.
func NewMockUpdateKeyOperation(ctrl *gomock.Controller) *MockUpdateKeyOperation {
	mock := &MockUpdateKeyOperation{ctrl: ctrl}
	mock.recorder = &MockUpdateKeyOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateKeyOperation) EXPECT() *MockUpdateKeyOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateKeyOperation) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateKeyOperationMockRecorder) Execute(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateKeyOperation)(nil).Execute), ctx, id)
}

// WithStorage mocks base method.
func (m *MockUpdateKeyOperation) WithStorage(storage logical.Storage) keys.UpdateKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.UpdateKeyOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockUpdateKeyOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockUpdateKeyOperation)(nil).WithStorage), storage)
}

// MockListKeysOperation is a mock of ListKeysOperation interface.
type MockListKeysOperation struct {
	ctrl     *gomock.Controller
	recorder *MockListKeysOperationMockRecorder
}

// MockListKeysOperationMockRecorder is the mock recorder for MockListKeysOperation.
type MockListKeysOperationMockRecorder struct {
	mock *MockListKeysOperation
}

// NewMockListKeysOperation creates a new mock instance.
func NewMockListKeysOperation(ctrl *gomock.Controller) *MockListKeysOperation {
	mock := &MockListKeysOperation{ctrl: ctrl}
	mock.recorder = &MockListKeysOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListKeysOperation) EXPECT() *MockListKeysOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListKeysOperation) Execute(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListKeysOperationMockRecorder) Execute(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListKeysOperation)(nil).Execute), ctx)
}

// WithStorage mocks base method.
func (m *MockListKeysOperation) WithStorage(storage logical.Storage) keys.ListKeysOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.ListKeysOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockListKeysOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockListKeysOperation)(nil).WithStorage), storage)
}

// MockImportKeyOperation is a mock of ImportKeyOperation interface.
type MockImportKeyOperation struct {
	ctrl     *gomock.Controller
	recorder *MockImportKeyOperationMockRecorder
}

// MockImportKeyOperationMockRecorder is the mock recorder for MockImportKeyOperation.
type MockImportKeyOperationMockRecorder struct {
	mock *MockImportKeyOperation
}

// NewMockImportKeyOperation creates a new mock instance.
func NewMockImportKeyOperation(ctrl *gomock.Controller) *MockImportKeyOperation {
	mock := &MockImportKeyOperation{ctrl: ctrl}
	mock.recorder = &MockImportKeyOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportKeyOperation) EXPECT() *MockImportKeyOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockImportKeyOperation) Execute(ctx context.Context, key *entities.PrivateKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockImportKeyOperationMockRecorder) Execute(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockImportKeyOperation)(nil).Execute), ctx, key)
}

// WithStorage mocks base method.
func (m *MockImportKeyOperation) WithStorage(storage logical.Storage) keys.ImportKeyOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStorage", storage)
	ret0, _ := ret[0].(keys.ImportKeyOperation)
	return ret0
}

// WithStorage indicates an expected call of WithStorage.
func (mr *MockImportKeyOperationMockRecorder) WithStorage(storage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStorage", reflect.TypeOf((*MockImportKeyOperation)(nil).WithStorage), storage)
}
