@vault_address = http://localhost:8200
@vault_dev_token = DevVaultToken

### Keys

### Create secp256k1
POST {{vault_address}}/v1/signer/keys
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"id":"secp256k1","curve":"secp256k1","metadata":{"owner":"Alice"}}

### Create ed25519
POST {{vault_address}}/v1/signer/keys
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"id":"ed25519","curve":"ed25519","metadata":{"owner":"Alice"}}

### Create p256
POST {{vault_address}}/v1/signer/keys
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"id":"p256","curve":"p256","metadata":{"owner":"Alice"}}

### List
GET {{vault_address}}/v1/signer/keys
X-Vault-Token: {{vault_dev_token}}

### Read
GET {{vault_address}}/v1/signer/keys/secp256k1
X-Vault-Token: {{vault_dev_token}}

### Sign hash
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/hash
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"hash":"a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"}

### Sign batch
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/batch
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"hashes":["a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3","b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"]}

### Sign message sha256
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/message
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"message":"68656c6c6f","hash_function":"sha256"}

### Sign message keccak256
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/message
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"message":"68656c6c6f","hash_function":"keccak256"}

### Sign message sha512
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/message
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"message":"68656c6c6f","hash_function":"sha512"}

### Sign message sha3-256
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/message
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{"message":"68656c6c6f","hash_function":"sha3-256"}

### Sign legacy Ethereum tx
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/ethereum/transaction
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{
    "type": "0x0",
    "nonce": "0x0",
    "to": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
    "value": "0xde0b6b3a7640000",
    "gas": "0x5208",
    "gasPrice": "0x4a817c800",
    "chainId": "0x1"
}

### Sign EIP-1559 Ethereum tx
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/ethereum/transaction
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{
    "type": "0x2",
    "nonce": "0x0",
    "to": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
    "value": "0xde0b6b3a7640000",
    "gas": "0x5208",
    "maxPriorityFeePerGas": "0x3b9aca00",
    "maxFeePerGas": "0x6fc23ac00",
    "chainId": "0x1"
}

### Sign EIP-712 typed data
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/ethereum/typed-data
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{
	"types": {
		"EIP712Domain": [
			{"name": "name", "type": "string"},
			{"name": "version", "type": "string"},
			{"name": "chainId", "type": "uint256"},
			{"name": "verifyingContract", "type": "address"}
		],
		"Person": [
			{"name": "name", "type": "string"},
			{"name": "wallet", "type": "address"}
		],
		"Mail": [
			{"name": "from", "type": "Person"},
			{"name": "to", "type": "Person"},
			{"name": "contents", "type": "string"}
		]
	},
	"primaryType": "Mail",
	"domain": {
		"name": "Ether Mail",
		"version": "1",
		"chainId": 1,
		"verifyingContract": "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
	},
	"message": {
		"from": {"name": "Cow", "wallet": "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826"},
		"to": {"name": "Bob", "wallet": "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB"},
		"contents": "Hello, Bob!"
	}
}

### Sign ERC-4337 UserOperation
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/ethereum/user-operation
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{
	"userOperation": {
		"sender": "0x9f22F7C0c9D5a27881D1b4A29d14A7F88547DdbD",
		"nonce": "0x7",
		"callData": "0xcafebabe",
		"callGasLimit": "0x249f0",
		"verificationGasLimit": "0x186a0",
		"preVerificationGas": "0xc350",
		"maxPriorityFeePerGas": "0x64",
		"maxFeePerGas": "0x3e8"
	},
	"entryPoint": "0x0000000071727De22E5E9d8bAF0edAc6f37da032",
	"entryPointVersion": "0.8",
	"chainId": "0x1"
}

### Sign ERC-4337 UserOperation with paymaster
POST {{vault_address}}/v1/signer/keys/secp256k1/sign/ethereum/user-operation
Content-Type: application/json
X-Vault-Token: {{vault_dev_token}}

{
	"userOperation": {
		"sender": "0x9f22F7C0c9D5a27881D1b4A29d14A7F88547DdbD",
		"nonce": "0x7",
		"callData": "0xcafebabe",
		"callGasLimit": "0x249f0",
		"verificationGasLimit": "0x186a0",
		"preVerificationGas": "0xc350",
		"maxPriorityFeePerGas": "0x64",
		"maxFeePerGas": "0x3e8",
		"paymaster": "0x0000000000000000000000000000000000000001",
		"paymasterVerificationGasLimit": "0xc350",
		"paymasterPostOpGasLimit": "0x7530",
		"paymasterData": "0xdeadbeef"
	},
	"entryPoint": "0x0000000071727De22E5E9d8bAF0edAc6f37da032",
	"entryPointVersion": "0.8",
	"chainId": "0x1"
}

### Delete
DELETE {{vault_address}}/v1/signer/keys/secp256k1
X-Vault-Token: {{vault_dev_token}}
