[tasks.test]
run = "go test -v -race -cover ./..."

[tasks.image]
run = "docker build -t vault-signer:latest ."

[tasks.'image:run']
depends = ["image"]
usage = '''
flag "--detach" help="Run container in detached mode"
'''
run = "docker run --rm -it -p 8200:8200 --name vault-signer vault-signer:latest {% if detach %}-d{% endif %}"

[tasks.'image:stop']
run = "docker stop vault-signer"
