[env]
PROJECT_NAME = "bc-signer"

[tasks.upgradedeps]
run = "go get -u ./..."

[tasks.test]
run = "go test -v -race -cover ./..."

[tasks.image]
run = [
    "docker build -t vault-signer:latest -f docker/Dockerfile .",
    "docker build -t vault-signer:0.0.1 -f docker/Dockerfile .",
]

[tasks.format]
run = "gofmt -s -w ."

[tasks.check]
run = ["go vet ./...", "golangci-lint run"]

[tasks.'service:run']
depends = ["image"]
usage = '''
flag "--detach" help="Run container in detached mode"
'''
run = "docker compose -p ${PROJECT_NAME} -f docker/docker-compose.macos.yaml up {% if detach %}-d{% endif %}"

[tasks.'service:stop']
run = "docker compose -p ${PROJECT_NAME} -f docker/docker-compose.macos.yaml stop"

[tasks.'service:down']
run = [
    "docker compose -p ${PROJECT_NAME} -f docker/docker-compose.macos.yaml down",
    "docker volume rm ${PROJECT_NAME}_vault-plugins",
]
