[tasks.upgradedeps]
run = "go get -u ./..."

[tasks.test]
run = "go test -v -race -cover ./..."

[tasks.image]
run = [
    "docker build -t vault-signer:latest -f docker/Dockerfile .",
    "docker build -t vault-signer:0.0.1 -f docker/Dockerfile .",
]

[tasks.format]
run = "gofmt -s -w ."

[tasks.check]
run = ["go vet ./...", "golangci-lint run"]

[tasks.'image:run']
depends = ["image"]
usage = '''
flag "--detach" help="Run container in detached mode"
'''
run = "docker run --rm -it -p 8200:8200 --name vault-signer vault-signer:latest {% if detach %}-d{% endif %}"

[tasks.'image:stop']
run = "docker stop vault-signer"
